### ISSUE TITLE
Minor Error. Amp Code

### ISSUE THREAD

**Issue by kalverra** [kttran/prj-rev-bwfs-dasmoto#1]
https://github.com/kttran/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L5

& is a special character in HTML, check here. http://rabbit.eng.miami.edu/info/htmlchars.html

**Comment by kttran** [comment]
Hi Kalverra,

Thank you for citing the embedded ampersand character is a HTML special character - '&amp;' and it should be encoded. 

I had missed this minor error as the title and heading1 in index.html rendered correctly on Google Chrome, nonetheless, I can suspect that the unencoded '&' can be filtered out on some other web browser.

I have edited and checked in the improvement.
